---
channel: stable
addons:
  autossh:
    repository: xchwarze/addon-autossh
    target: autossh
    image: autossh
  transmission:
    repository: xchwarze/addon-transmission
    target: transmission
    image: transmission
